### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Midoritotoro** [WALTERXO/telegram-grabber#1]
Странно, бот работает только при первом запуске скрипта, когда спрашивается номер телефона. Можно ли ввести подтверждение номера после каждого запуска файла?

**Comment by WALTERXO** [comment]
@Midoritotoro после каждого запуска нужно соответствие (/set_channel_mapping) устанавливать заново оно не сохраняется.

**Comment by maxty9378** [comment]
> Странно, бот работает только при первом запуске скрипта, когда спрашивается номер телефона. Можно ли ввести подтверждение номера после каждого запуска файла?

Можно немного изменить код. Сессия сохранится.
`# Создание клиента Telegram 
client = TelegramClient('session_name', api_id, api_hash, system_version="4.16.30-vxMAX")`
