### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by araneon** [WALTERXO/telegram-grabber#10]
Не получается нормально запустить бота, при старте main.py в бота приходит сообщение что "Бот запущен" но больше ничего не происходит, бот ни на какие команды не реагирует. Если остановить бота (через IDE) то бот пишет "Бот остановлен".
При запуске main.py в терминале пишет 3 строки:

INFO:__main__:GRAB - Запущен
INFO:telethon.network.mtprotosender:Connecting to IP:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to IP:443/TcpFull complete!

И всё, нет никаких запросов телефона и кода подтверждения от Телеграм.
При этом файл myGrab.session создаётся, и заполняется данными dc_id, server_address, port, auth_key (BOLT)

**Comment by WALTERXO** [comment]
@araneon т.е. вы авторизацию вообще не проходили?

**Comment by araneon** [comment]
Авторизации по телефону, с отправкой кода подтверждения у меня не происходит.
Что я делал:
Ранее создавал api_id и api_hash, для другой задачи, прописал их в соответствующие поля в коде.
Создал бота, токен прописал в bot_token
moderation_active изменил на True (не знаю, нужно ли это или нет )))))
technical_channel_id прописал ID технического канала (предварительно его только что создав)
Заменил new_link и все встречающиеся в коде слова test.
Указал свой chat_id
Создал канал, добавил туда бота  и сделал его админом.
Запускаю main.py, в ответ получаю

INFO:main:GRAB - Запущен
INFO:telethon.network.mtprotosender:Connecting to IP:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to IP:443/TcpFull complete!

И всё, больше ничего не происходит.
P/S/ доэксперементировался, теперь и в телегу не пускает, выкинуло со всех устройств и не даёт зайти заново, phone_code_expired)))

**Comment by WALTERXO** [comment]
@araneon 
moderation_active верните на False, активировать его можно прямо в боте. Если у вас даже авторизации не было, то не может в телеграм не пускать из-за этого. Оставьте ваш телеграм я с вами свяжусь.

**Comment by araneon** [comment]
ок, спасибо большое N2_N_a_m_E

**Comment by araneon** [comment]
Если долго мучиться, то что-то да получится )))
![изображение_2024-01-09_175536764](https://github.com/WALTERXO/telegram-grabber/assets/18113701/0ec90c2c-d5cf-4219-9f79-73146d107fbc)
Вроде запустил, в боте показались кнопки и сразу из телеги выкинуло )))
Теперь при попытке заново зайти, пишет, слишком много попыток.

**Comment by Therealwh** [comment]
> Если долго мучиться, то что-то да получится ))) ![изображение_2024-01-09_175536764](https://private-user-images.githubusercontent.com/18113701/295243868-0ec90c2c-d5cf-4219-9f79-73146d107fbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4NDM4NTIsIm5iZiI6MTcwNDg0MzU1MiwicGF0aCI6Ii8xODExMzcwMS8yOTUyNDM4NjgtMGVjOTBjMmMtZDVjZi00MjE5LTlmNzktNzMxNDZkMTA3ZmJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIzMzkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4Mjc1Y2JiZmRiOTE0NDdlMjFlNzk1OWExNjhmYjJlNWUzMTZkYjdiNGFjMDJiYTFhYmQyNzExODRhMjIzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3ZIVOXL4egloNLEQGwVvdvN1CjCJ2LEpbP8yNxdslfU) Вроде запустил, в боте показались кнопки и сразу из телеги выкинуло ))) Теперь при попытке заново зайти, пишет, слишком много попыток.


Привет, чтоб не вылетало с устройств допиши как у меня в файле, и не будет вылетать.
![Screenshot_113](https://github.com/WALTERXO/telegram-grabber/assets/149853905/2de2729a-9781-4ce0-90a8-d8fbc0064d2b)

**Comment by Therealwh** [comment]
@araneon    
![Screenshot_113](https://github.com/WALTERXO/telegram-grabber/assets/149853905/593d282d-0f38-41dc-bd5f-c6f835b0e341)
Привет, чтоб не вылетало с устройств допиши как у меня в файле, и не будет вылетать.

**Comment by araneon** [comment]
ООО Господа, великодушное МЕРСИ !!!
Супер, бот запустился, кнопочки показал, с клиента на телефоне не выкидывает !!!

**Comment by WALTERXO** [comment]
@Therealwh как я понимаю задаётся версия api клиента? У меня просто данной проблемы с выкидыванием ни на одном тестовом аккаунте не было. Поэтому думал, что у вас просто аккаунты много подозрительных манипуляций совершали

**Comment by Therealwh** [comment]
@WALTERXO  Ну я так понял, что если на пк запушен акк то когда через бота запускаешь совпадает версия системы. И поэтому подозрительно и он выкидывает всех с аккаунта. Если прописать версию то все норм нет совпадений.

**Comment by WALTERXO** [comment]
@Therealwh это если вы до этого тестили модерацию и на включённом режиме закрыли. А потом снова запустили и нажали "Модерация: выкл". При перезапуске нужно заново /start прописывать. Оно актуальное значение показывает. 

А если вы про сами кнопки: 
![image](https://github.com/WALTERXO/telegram-grabber/assets/91873172/1da70782-89f0-40a8-a6ab-c01eee4fa108)
 то они и должны работать так. Чтобы включить модерацию нужно нажать "Модерация: вкл", ну и наоборот чтобы выключить
