### ISSUE TITLE
Не берет больше одного поста, либо фотографии

### ISSUE THREAD

**Issue by f1nik76** [WALTERXO/telegram-grabber#13]
Такая проблема, с поста где несколько фото бот берет только одну последнюю фотку. Попробовал другой канал с одной фоткой, то одно сообщение берет, и все. какое количество не ставлю просто тишина, и ошибок в логе нет. /last_messages без числа работает, с all или числом - нет. 

p.s. Тестирую с клиента на маке.

**Comment by f1nik76** [comment]
Разобрался спасибо)

**Comment by WALTERXO** [comment]
@f1nik76 если в одном сообщение 10 фоток, то они считаются как 10 сообщений

**Comment by f1nik76** [comment]
Теперь думаю как ссылки фильтровать и заменять на свои. Он просто сейчас все ссылки меняет на одну.
