### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vladick-228** [WALTERXO/telegram-grabber#19]
`INFO:__main__:GRAB - Запущен
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51:443/TcpFull complete!
INFO:telethon.network.mtprotosender:User is already connected!
INFO:aiogram.dispatcher.dispatcher:Start polling.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-37' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=MessageNotModified('Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message')>
Traceback (most recent call last):
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\Desktop\telegram-grabber-main\main.py", line 495, in toggle_moderation
    await bot.edit_message_reply_markup(callback_query.message.chat.id, callback_query.message.message_id, reply_markup=keyboard)
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\bot.py", line 3252, in edit_message_reply_markup
    result = await self.request(api.Methods.EDIT_MESSAGE_REPLY_MARKUP, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "C:\Users\divergent\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
`

**Comment by vladick-228** [comment]
`aiogram.utils.exceptions.MessageNotModified: Message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
INFO:telethon.client.updates:Got difference for account updates
INFO:telethon.client.updates:Got difference for channel 1170977746 updates
INFO:telethon.client.updates:Got difference for channel 1754252633 updates
INFO:telethon.client.updates:Got difference for channel 1291078006 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1156969946 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1596957400 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1737035280 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1156969946 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1156969946 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1737035280 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1737035280 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1156969946 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1682306812 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1409551458 updates
INFO:telethon.client.updates:Got difference for channel 1469492540 updates`

Бесконечный апдейт, в техничку не приходят

**Comment by WALTERXO** [comment]
@vladick-228 нужно больше информации плюс проверьте все настройки по инструкции

**Comment by WALTERXO** [comment]
@vladick-228 не забудьте также про заполнение конфига

**Comment by vladick-228** [comment]
Проблема решилась подвязкой каналов соответствий, делайте все по инструкции и все будет замечательно. Автору респект!
