### ISSUE TITLE
Не работает с чат группой разделенной на темы. 

### ISSUE THREAD

**Issue by DGproj** [WALTERXO/telegram-grabber#2]
Бот рабочий. Но если попытаться добавить в него канал который разделен на темы, он не правильно записывает id темы. id тем пишутся в формате: nnnnnn_m, а при добавлении в destination_channels "_" пропускается и получается формат nnnnnnm. Либо я чего-то не понял, либо будет хорошо добавить такую возможность. Спасибо.

**Comment by Ariyts** [comment]
[DGproj](https://github.com/DGproj) можете указать Ваш телеграм.. есть несколько вопросов по поводу установки данного бота.. Либо напишите мне в телегу: @Ariyts
@DGproj @WALTERXO собственно вопросы по установке данного бота
Буду признателен если откликнетесь

**Comment by WALTERXO** [comment]
@Ariyts @DGproj  Пересылка сообщений из группы, в которой есть "Темы" не планируется добавляться
