### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by CapitanYlitka** [WALTERXO/telegram-grabber#20]
Никак не получается пройти авторизацию. Заполнил хэши, апи и прочее. Запускаю ботинка. В чат приходит сообщение, что бот запущен и на этом все. До телефона не доходит. В чем проблема - хз. Проверил уже все по 150 раз. Ошибок тоже никаких не выводит.
![image](https://github.com/WALTERXO/telegram-grabber/assets/98390077/8b1094a4-c915-4ead-8d26-4e190f3f7b04)

Мой ТГ: @CapitanYlitka

**Comment by Therealwh** [comment]
После обновления скрипт сломался, в сам файл был добавлен new_username  которого в конфиге нет. Ну и если удалить все напоминания о new_username все равно не приходят сообщения ни в тех канал ни без него. Откатился обратно.

**Comment by WALTERXO** [comment]
@Therealwh в RoadMap написал, что конфиг обновлён, его тоже нужно заново качать. new_username есть в новом конфиге

**Comment by Therealwh** [comment]
@WALTERXO  в архиве еще не обновлен файл получается?

**Comment by WALTERXO** [comment]
@Therealwh new_username по сути это старый replase . Обновил потому что изначально нейминг странный дал и он каждый раз сбивал

**Comment by WALTERXO** [comment]
@Therealwh Обновлён

**Comment by DamDage** [comment]
![2024-01-25_01-11-53](https://github.com/WALTERXO/telegram-grabber/assets/153467433/ef25f4fb-e066-4096-a388-f41d67c30ed6)
тоже самое. Миллион раз пытался запустить, но не до регистрации с номером не доходит

**Comment by gaolersan** [comment]
@DamDage У меня была проблема с авторизацией из-за облачного пароля. Пришлось отключить его, пройти авторизацию и потом уже включить обратно. Может быть тут тоже самое.

**Comment by WALTERXO** [comment]
@CapitanYlitka решили в лс удалением питона, и скачиваем версии 3.11

@gaolersan у меня тоже облачный пароль стоит, но всё норм проходит, его тоже просто запращивает

@DamDage удалите python, перезагрузите пк, установите заново версию 3.11, установите библиотеки

**Comment by DamDage** [comment]
> @CapitanYlitka решили в лс удалением питона, и скачиваем версии 3.11
> 
> @gaolersan у меня тоже облачный пароль стоит, но всё норм проходит, его тоже просто запращивает
> 
> @DamDage удалите python, перезагрузите пк, установите заново версию 3.11, установите библиотеки

Заработало. Но появилась еще одна проблема. Спустя 3-4 минуты после использования аккаунт банят

**Comment by Therealwh** [comment]
@DamDage Что значит банят? не должны банить, два аккаунта в работе ни одного бана. Раньше могло вылетать  но автор добавил подмену клиента...

**Comment by DamDage** [comment]
> @DamDage Что значит банят? не должны банить, два аккаунта в работе ни одного бана. Раньше могло вылетать но автор добавил подмену клиента...

У меня был аккаунт телеграмм чей номер я указывал при создании сессии. Все работало 5 минут и аккаунт удалили :(

**Comment by CapitanYlitka** [comment]
Для тех у кого такая проблема, ловите решение.

1. Для начала запустите скрипт на локальном ПК. Для этого качаем VScode. Качаем питон версии 3.11.3.
2. Открываем проект в VScode, выбираем питон который скачали. Редактируем конфиг по инструкции автора. Качаем библиотеки так же по инструкции. Запускаем main.py.
3. Если все работает то настраиваем до конца и сохраняем.
4. После полной настройки можно заливать на сервер СО ВСЕМИ ФАЙЛАМИ ВКЛЮЧАЯ СОЗДАННЫЕ СКРИПТОМ. 
5. Обратите внимание, что на сервере должен так же стоять питон версии 3.11 и все библиотеки. К слову у меня на сервере уже стоял один бот на питоне 3.8+node+mongo. Данный скрипт на нем не запускается! Нужно ставить второй питон. В интернете инструкция как использовать два питона на одном сервере есть. Там есть свои нюансы для запуска. Например команда для запуска будет уже выглядеть так: python3.11 main.py .

Так же у вас может быть такая проблема: вы зашли в ssh-консоль, запустили бота, все работает. Закрываете сеанс ssh и бот перестает работать. Это происходит потому, что на некоторых серверах файл исполняется только до тех пор, пока есть активные сессии. Как только сессия закрывается, скрипт тоже завершается. Чтобы такого не происходило скрипт можно запустить либо через screen, либо через nohup. Бот будет работать даже после завершения сессии. До тех пор пока не ляжет сервак)

Подытожим. Если у вас на сервере стоят два питона разных версий и скрипт закрывается при завершении сессии в ssh, то команда для запуска будет выглядеть так: nohup python3.11 main.py

Надеюсь это кому-то поможет. При возникновении ошибок при работе в ssh-клиенте, не ленитесь гуглить. Копируете ошибку и ищите ответ на свой вопрос. Да - долго, да - не просто, да - нихера не понятно. Но если уж вы полезли в ботов, то старайтесь разбираться. Это поможет вам развивать свои проекты и чинить их самостоятельно. Помочь, подсказать - вам помогут, но решать за вас возникающие варнинги просто так вряд-ли кто-то будет. 

Лично мне, чтобы запустить уже настроенного бота на сервере потребовалось потратить почти целый день. Но это того стоило)

Всем удачи !
