### ISSUE TITLE
Отключить замену ссылок

### ISSUE THREAD

**Issue by f1nik76** [WALTERXO/telegram-grabber#21]
Добрый вечер. Предлагаю в будущих обновлениях дать пользователям возможность включать или отключать замену ссылок в режиме модерации. Ну или глобально. Сейчас он меняет все ссылки на одну. Даже полезные в тексте.

**Comment by WALTERXO** [comment]
@f1nik76 через несколько недель планируется выход платной версии, там уже реализована эта функция

**Comment by f1nik76** [comment]
Спасибо, ждем)
