### ISSUE TITLE
Бот не работает после обновления.

### ISSUE THREAD

**Issue by f1nik76** [WALTERXO/telegram-grabber#22]
В чем может быть проблема. Остановил бота, обновил файлы, в конфиге оставил первые 4 строчки. Запустил бота, все стартануло без проблем, но посты не грабит. Улдалил привязку, группы связал заново. Ничего не поменялось. В чем может быть проблема?

**Comment by WALTERXO** [comment]
@f1nik76 перепроверьте конфиг, он такой же?
![image](https://github.com/WALTERXO/telegram-grabber/assets/91873172/2c7ca07b-b900-4293-ad1d-8a8320ebde4e)

**Comment by f1nik76** [comment]
`api_id =
api_hash = ''
bot_token = ''
my_id =

technical_channel_id = - # ID технического канала

new_link = "http://t.me/"
new_username = "@"

proxy_url = 'http://ip:port'  #заполнять только если планируете рерайтить текст в режиме модерации с помощью Chat GPT
openai_api_key = "sk-..."  #заполнять только если планируете рерайтить текст в режиме модерации с помощью Chat GPT
`

Да, тоже самое


![image](https://github.com/WALTERXO/telegram-grabber/assets/70451660/d1dd9faa-9254-44ec-a820-60e7c70760b7)


Вот лог с терминала

**Comment by f1nik76** [comment]
в группы надо вступить, с которых грабим посты? А то я из них вышел, но бот работал

**Comment by f1nik76** [comment]
Вступил в каналы, посты стали прилетать. Думаю надо добавить в faq
