### ISSUE TITLE
Сложности с ботом

### ISSUE THREAD

**Issue by rvoznak** [WALTERXO/telegram-grabber#9]
Не могу запустить. Библиотеки установил. Сделал всё по инструкции. При первом запуске запускает GRAB, но дальше уходить в ошибку. Сам не программист, поэтому мало в этом разбираюсь. 
![Безымянный](https://github.com/WALTERXO/telegram-grabber/assets/150127347/594d1b85-a8b1-4add-9b1e-b6d560c3523d)

**Comment by rvoznak** [comment]
Ошибок в коде не выдает (нет красных линий)

**Comment by WALTERXO** [comment]
@rvoznak вы вот тут свой id написали?
![image](https://github.com/WALTERXO/telegram-grabber/assets/91873172/60baf8ce-d3c9-4b40-b82e-ebf19bd14bdd)

**Comment by WALTERXO** [comment]
@rvoznak нужно брать из первой строчки в https://t.me/getmyid_bot
![image](https://github.com/WALTERXO/telegram-grabber/assets/91873172/0ca8bc6e-7110-4bf6-a9cd-0727173a89ab)

**Comment by WALTERXO** [comment]
Он у каждого свой
